ammQuote: 1
referrals:
  deribit: lienparrainage
  thales: lienparrainage
rpc:
  ethereum: url+apikey
  optimism: url+apikey
  polygon: url+apikey
  solana: url+apikey
  serum: https://solana-api.projectserum.com
