/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ExoticHeader: typeof import('./src/components/widgets/ExoticHeader.vue')['default']
    ExtraHeader: typeof import('./src/components/widgets/ExtraHeader.vue')['default']
    GenericDatatable: typeof import('./src/components/GenericDatatable.vue')['default']
    HeaderDropdown: typeof import('./src/components/widgets/HeaderDropdown.vue')['default']
    HeaderSelectDropdown: typeof import('./src/components/widgets/HeaderSelectDropdown.vue')['default']
    IAkarIconsArrowRight: typeof import('~icons/akar-icons/arrow-right')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    IAntDesignGithubFilled: typeof import('~icons/ant-design/github-filled')['default']
    'ICarbon:number1': typeof import('~icons/carbon/number1')['default']
    'ICarbon:number2': typeof import('~icons/carbon/number2')['default']
    'ICarbon:number3': typeof import('~icons/carbon/number3')['default']
    'IEl:checkEmpty': typeof import('~icons/el/check-empty')['default']
    IEosIconsBlockchain: typeof import('~icons/eos-icons/blockchain')['default']
    IEosIconsBubbleLoading: typeof import('~icons/eos-icons/bubble-loading')['default']
    IFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    'ILucide:copyCheck': typeof import('~icons/lucide/copy-check')['default']
    'IMdi:checkboxMultipleMarkedOutline': typeof import('~icons/mdi/checkbox-multiple-marked-outline')['default']
    'IMdi:closeBoxMultipleOutline': typeof import('~icons/mdi/close-box-multiple-outline')['default']
    LoadingIndicator: typeof import('./src/components/widgets/LoadingIndicator.vue')['default']
    MobileRenderer: typeof import('./src/components/widgets/MobileRenderer.vue')['default']
    PresetsList: typeof import('./src/components/PresetsList.vue')['default']
    PresetsSelect: typeof import('./src/components/PresetsSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}
