// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    DropdownFilterset: typeof import('./src/components/widgets/DropdownFilterset.vue')['default']
    ExoticHeader: typeof import('./src/components/widgets/ExoticHeader.vue')['default']
    ExtraHeader: typeof import('./src/components/widgets/ExtraHeader.vue')['default']
    GenericDatatable: typeof import('./src/components/GenericDatatable.vue')['default']
    HeaderDropdown: typeof import('./src/components/widgets/HeaderDropdown.vue')['default']
    'HeaderDropdown copy': typeof import('./src/components/widgets/HeaderDropdown copy.vue')['default']
    HeaderSelectDropdown: typeof import('./src/components/widgets/HeaderSelectDropdown.vue')['default']
    HeaderSimpleDropdown: typeof import('./src/components/widgets/HeaderSimpleDropdown.vue')['default']
    IAkarIconsArrowRight: typeof import('~icons/akar-icons/arrow-right')['default']
    IAkarIconsGithubFill: typeof import('~icons/akar-icons/github-fill')['default']
    IAntDesignGithubFilled: typeof import('~icons/ant-design/github-filled')['default']
    'ICarbon:number1': typeof import('~icons/carbon/number1')['default']
    'ICarbon:number2': typeof import('~icons/carbon/number2')['default']
    'ICarbon:number3': typeof import('~icons/carbon/number3')['default']
    IEosIconsBlockchain: typeof import('~icons/eos-icons/blockchain')['default']
    IEosIconsBubbleLoading: typeof import('~icons/eos-icons/bubble-loading')['default']
    IFaSolidMoon: typeof import('~icons/fa-solid/moon')['default']
    IFaSolidSun: typeof import('~icons/fa-solid/sun')['default']
    IIonArrowBackOutline: typeof import('~icons/ion/arrow-back-outline')['default']
    LoadingIndicator: typeof import('./src/components/widgets/LoadingIndicator.vue')['default']
    MobileRenderer: typeof import('./src/components/widgets/MobileRenderer.vue')['default']
    PresetsList: typeof import('./src/components/PresetsList.vue')['default']
    PresetsSelect: typeof import('./src/components/PresetsSelect.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
  }
}

export { }
