// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package thales

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// AllLiveMarketsMarket includes the requested fields of the GraphQL type Market.
type AllLiveMarketsMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	Result       int    `json:"result"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns AllLiveMarketsMarket.Id, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetId() string { return v.Id }

// GetTimestamp returns AllLiveMarketsMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns AllLiveMarketsMarket.Creator, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns AllLiveMarketsMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetStrikePrice returns AllLiveMarketsMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetStrikePrice() string { return v.StrikePrice }

// GetMaturityDate returns AllLiveMarketsMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetMaturityDate() string { return v.MaturityDate }

// GetExpiryDate returns AllLiveMarketsMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetExpiryDate() string { return v.ExpiryDate }

// GetIsOpen returns AllLiveMarketsMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetIsOpen() bool { return v.IsOpen }

// GetResult returns AllLiveMarketsMarket.Result, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetResult() int { return v.Result }

// GetLongAddress returns AllLiveMarketsMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetLongAddress() string { return v.LongAddress }

// GetShortAddress returns AllLiveMarketsMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetShortAddress() string { return v.ShortAddress }

// GetFinalPrice returns AllLiveMarketsMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *AllLiveMarketsMarket) GetFinalPrice() string { return v.FinalPrice }

// AllLiveResponse is returned by AllLive on success.
type AllLiveResponse struct {
	Markets []AllLiveMarketsMarket `json:"markets"`
}

// GetMarkets returns AllLiveResponse.Markets, and is useful for accessing the field via an interface.
func (v *AllLiveResponse) GetMarkets() []AllLiveMarketsMarket { return v.Markets }

// AllMarketsMarketsMarket includes the requested fields of the GraphQL type Market.
type AllMarketsMarketsMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns AllMarketsMarketsMarket.Id, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetId() string { return v.Id }

// GetTimestamp returns AllMarketsMarketsMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns AllMarketsMarketsMarket.Creator, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns AllMarketsMarketsMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetStrikePrice returns AllMarketsMarketsMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetStrikePrice() string { return v.StrikePrice }

// GetMaturityDate returns AllMarketsMarketsMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetMaturityDate() string { return v.MaturityDate }

// GetExpiryDate returns AllMarketsMarketsMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetExpiryDate() string { return v.ExpiryDate }

// GetIsOpen returns AllMarketsMarketsMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns AllMarketsMarketsMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns AllMarketsMarketsMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetLongAddress() string { return v.LongAddress }

// GetShortAddress returns AllMarketsMarketsMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetShortAddress() string { return v.ShortAddress }

// GetResult returns AllMarketsMarketsMarket.Result, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetResult() int { return v.Result }

// GetCustomMarket returns AllMarketsMarketsMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetCustomMarket() bool { return v.CustomMarket }

// GetCustomOracle returns AllMarketsMarketsMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetCustomOracle() string { return v.CustomOracle }

// GetFinalPrice returns AllMarketsMarketsMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *AllMarketsMarketsMarket) GetFinalPrice() string { return v.FinalPrice }

// AllMarketsResponse is returned by AllMarkets on success.
type AllMarketsResponse struct {
	Markets []AllMarketsMarketsMarket `json:"markets"`
}

// GetMarkets returns AllMarketsResponse.Markets, and is useful for accessing the field via an interface.
func (v *AllMarketsResponse) GetMarkets() []AllMarketsMarketsMarket { return v.Markets }

// AllRangedMarketsRangedMarketsRangedMarket includes the requested fields of the GraphQL type RangedMarket.
type AllRangedMarketsRangedMarketsRangedMarket struct {
	Id           string                                               `json:"id"`
	Timestamp    string                                               `json:"timestamp"`
	CurrencyKey  string                                               `json:"currencyKey"`
	MaturityDate string                                               `json:"maturityDate"`
	LeftPrice    string                                               `json:"leftPrice"`
	RightPrice   string                                               `json:"rightPrice"`
	InAddress    string                                               `json:"inAddress"`
	OutAddress   string                                               `json:"outAddress"`
	RightMarket  AllRangedMarketsRangedMarketsRangedMarketRightMarket `json:"rightMarket"`
	LeftMarket   AllRangedMarketsRangedMarketsRangedMarketLeftMarket  `json:"leftMarket"`
	IsOpen       bool                                                 `json:"isOpen"`
	Result       int                                                  `json:"result"`
	FinalPrice   string                                               `json:"finalPrice"`
}

// GetId returns AllRangedMarketsRangedMarketsRangedMarket.Id, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetId() string { return v.Id }

// GetTimestamp returns AllRangedMarketsRangedMarketsRangedMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetTimestamp() string { return v.Timestamp }

// GetCurrencyKey returns AllRangedMarketsRangedMarketsRangedMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetMaturityDate returns AllRangedMarketsRangedMarketsRangedMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetMaturityDate() string { return v.MaturityDate }

// GetLeftPrice returns AllRangedMarketsRangedMarketsRangedMarket.LeftPrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetLeftPrice() string { return v.LeftPrice }

// GetRightPrice returns AllRangedMarketsRangedMarketsRangedMarket.RightPrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetRightPrice() string { return v.RightPrice }

// GetInAddress returns AllRangedMarketsRangedMarketsRangedMarket.InAddress, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetInAddress() string { return v.InAddress }

// GetOutAddress returns AllRangedMarketsRangedMarketsRangedMarket.OutAddress, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetOutAddress() string { return v.OutAddress }

// GetRightMarket returns AllRangedMarketsRangedMarketsRangedMarket.RightMarket, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetRightMarket() AllRangedMarketsRangedMarketsRangedMarketRightMarket {
	return v.RightMarket
}

// GetLeftMarket returns AllRangedMarketsRangedMarketsRangedMarket.LeftMarket, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetLeftMarket() AllRangedMarketsRangedMarketsRangedMarketLeftMarket {
	return v.LeftMarket
}

// GetIsOpen returns AllRangedMarketsRangedMarketsRangedMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetIsOpen() bool { return v.IsOpen }

// GetResult returns AllRangedMarketsRangedMarketsRangedMarket.Result, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetResult() int { return v.Result }

// GetFinalPrice returns AllRangedMarketsRangedMarketsRangedMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarket) GetFinalPrice() string { return v.FinalPrice }

// AllRangedMarketsRangedMarketsRangedMarketLeftMarket includes the requested fields of the GraphQL type Market.
type AllRangedMarketsRangedMarketsRangedMarketLeftMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.Id, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetId() string { return v.Id }

// GetTimestamp returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetTimestamp() string {
	return v.Timestamp
}

// GetCreator returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.Creator, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetCurrencyKey() string {
	return v.CurrencyKey
}

// GetStrikePrice returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetStrikePrice() string {
	return v.StrikePrice
}

// GetMaturityDate returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetMaturityDate() string {
	return v.MaturityDate
}

// GetExpiryDate returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetExpiryDate() string {
	return v.ExpiryDate
}

// GetIsOpen returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetLongAddress() string {
	return v.LongAddress
}

// GetShortAddress returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetShortAddress() string {
	return v.ShortAddress
}

// GetResult returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.Result, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetResult() int { return v.Result }

// GetCustomMarket returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetCustomMarket() bool {
	return v.CustomMarket
}

// GetCustomOracle returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetCustomOracle() string {
	return v.CustomOracle
}

// GetFinalPrice returns AllRangedMarketsRangedMarketsRangedMarketLeftMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketLeftMarket) GetFinalPrice() string {
	return v.FinalPrice
}

// AllRangedMarketsRangedMarketsRangedMarketRightMarket includes the requested fields of the GraphQL type Market.
type AllRangedMarketsRangedMarketsRangedMarketRightMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.Id, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetId() string { return v.Id }

// GetTimestamp returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetTimestamp() string {
	return v.Timestamp
}

// GetCreator returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.Creator, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetCurrencyKey() string {
	return v.CurrencyKey
}

// GetStrikePrice returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetStrikePrice() string {
	return v.StrikePrice
}

// GetMaturityDate returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetMaturityDate() string {
	return v.MaturityDate
}

// GetExpiryDate returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetExpiryDate() string {
	return v.ExpiryDate
}

// GetIsOpen returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetPoolSize() string {
	return v.PoolSize
}

// GetLongAddress returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetLongAddress() string {
	return v.LongAddress
}

// GetShortAddress returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetShortAddress() string {
	return v.ShortAddress
}

// GetResult returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.Result, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetResult() int { return v.Result }

// GetCustomMarket returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetCustomMarket() bool {
	return v.CustomMarket
}

// GetCustomOracle returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetCustomOracle() string {
	return v.CustomOracle
}

// GetFinalPrice returns AllRangedMarketsRangedMarketsRangedMarketRightMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsRangedMarketsRangedMarketRightMarket) GetFinalPrice() string {
	return v.FinalPrice
}

// AllRangedMarketsResponse is returned by AllRangedMarkets on success.
type AllRangedMarketsResponse struct {
	RangedMarkets []AllRangedMarketsRangedMarketsRangedMarket `json:"rangedMarkets"`
}

// GetRangedMarkets returns AllRangedMarketsResponse.RangedMarkets, and is useful for accessing the field via an interface.
func (v *AllRangedMarketsResponse) GetRangedMarkets() []AllRangedMarketsRangedMarketsRangedMarket {
	return v.RangedMarkets
}

// MarketMarket includes the requested fields of the GraphQL type Market.
type MarketMarket struct {
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetTimestamp returns MarketMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns MarketMarket.Creator, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns MarketMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetStrikePrice returns MarketMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetStrikePrice() string { return v.StrikePrice }

// GetMaturityDate returns MarketMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetMaturityDate() string { return v.MaturityDate }

// GetExpiryDate returns MarketMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetExpiryDate() string { return v.ExpiryDate }

// GetIsOpen returns MarketMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns MarketMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns MarketMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetLongAddress() string { return v.LongAddress }

// GetShortAddress returns MarketMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetShortAddress() string { return v.ShortAddress }

// GetResult returns MarketMarket.Result, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetResult() int { return v.Result }

// GetCustomMarket returns MarketMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetCustomMarket() bool { return v.CustomMarket }

// GetCustomOracle returns MarketMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetCustomOracle() string { return v.CustomOracle }

// GetFinalPrice returns MarketMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *MarketMarket) GetFinalPrice() string { return v.FinalPrice }

// MarketResponse is returned by Market on success.
type MarketResponse struct {
	Market MarketMarket `json:"market"`
}

// GetMarket returns MarketResponse.Market, and is useful for accessing the field via an interface.
func (v *MarketResponse) GetMarket() MarketMarket { return v.Market }

// MarketsMarketsMarket includes the requested fields of the GraphQL type Market.
type MarketsMarketsMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns MarketsMarketsMarket.Id, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetId() string { return v.Id }

// GetTimestamp returns MarketsMarketsMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns MarketsMarketsMarket.Creator, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns MarketsMarketsMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetStrikePrice returns MarketsMarketsMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetStrikePrice() string { return v.StrikePrice }

// GetMaturityDate returns MarketsMarketsMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetMaturityDate() string { return v.MaturityDate }

// GetExpiryDate returns MarketsMarketsMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetExpiryDate() string { return v.ExpiryDate }

// GetIsOpen returns MarketsMarketsMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns MarketsMarketsMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns MarketsMarketsMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetLongAddress() string { return v.LongAddress }

// GetShortAddress returns MarketsMarketsMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetShortAddress() string { return v.ShortAddress }

// GetResult returns MarketsMarketsMarket.Result, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetResult() int { return v.Result }

// GetCustomMarket returns MarketsMarketsMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetCustomMarket() bool { return v.CustomMarket }

// GetCustomOracle returns MarketsMarketsMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetCustomOracle() string { return v.CustomOracle }

// GetFinalPrice returns MarketsMarketsMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *MarketsMarketsMarket) GetFinalPrice() string { return v.FinalPrice }

// MarketsResponse is returned by Markets on success.
type MarketsResponse struct {
	Markets []MarketsMarketsMarket `json:"markets"`
}

// GetMarkets returns MarketsResponse.Markets, and is useful for accessing the field via an interface.
func (v *MarketsResponse) GetMarkets() []MarketsMarketsMarket { return v.Markets }

// RangedMarketRangedMarket includes the requested fields of the GraphQL type RangedMarket.
type RangedMarketRangedMarket struct {
	Timestamp    string                              `json:"timestamp"`
	CurrencyKey  string                              `json:"currencyKey"`
	MaturityDate string                              `json:"maturityDate"`
	LeftPrice    string                              `json:"leftPrice"`
	RightPrice   string                              `json:"rightPrice"`
	InAddress    string                              `json:"inAddress"`
	OutAddress   string                              `json:"outAddress"`
	RightMarket  RangedMarketRangedMarketRightMarket `json:"rightMarket"`
	LeftMarket   RangedMarketRangedMarketLeftMarket  `json:"leftMarket"`
	IsOpen       bool                                `json:"isOpen"`
	Result       int                                 `json:"result"`
	FinalPrice   string                              `json:"finalPrice"`
}

// GetTimestamp returns RangedMarketRangedMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetTimestamp() string { return v.Timestamp }

// GetCurrencyKey returns RangedMarketRangedMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetMaturityDate returns RangedMarketRangedMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetMaturityDate() string { return v.MaturityDate }

// GetLeftPrice returns RangedMarketRangedMarket.LeftPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetLeftPrice() string { return v.LeftPrice }

// GetRightPrice returns RangedMarketRangedMarket.RightPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetRightPrice() string { return v.RightPrice }

// GetInAddress returns RangedMarketRangedMarket.InAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetInAddress() string { return v.InAddress }

// GetOutAddress returns RangedMarketRangedMarket.OutAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetOutAddress() string { return v.OutAddress }

// GetRightMarket returns RangedMarketRangedMarket.RightMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetRightMarket() RangedMarketRangedMarketRightMarket {
	return v.RightMarket
}

// GetLeftMarket returns RangedMarketRangedMarket.LeftMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetLeftMarket() RangedMarketRangedMarketLeftMarket {
	return v.LeftMarket
}

// GetIsOpen returns RangedMarketRangedMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetIsOpen() bool { return v.IsOpen }

// GetResult returns RangedMarketRangedMarket.Result, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetResult() int { return v.Result }

// GetFinalPrice returns RangedMarketRangedMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarket) GetFinalPrice() string { return v.FinalPrice }

// RangedMarketRangedMarketLeftMarket includes the requested fields of the GraphQL type Market.
type RangedMarketRangedMarketLeftMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns RangedMarketRangedMarketLeftMarket.Id, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetId() string { return v.Id }

// GetTimestamp returns RangedMarketRangedMarketLeftMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns RangedMarketRangedMarketLeftMarket.Creator, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns RangedMarketRangedMarketLeftMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetStrikePrice returns RangedMarketRangedMarketLeftMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetStrikePrice() string { return v.StrikePrice }

// GetMaturityDate returns RangedMarketRangedMarketLeftMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetMaturityDate() string { return v.MaturityDate }

// GetExpiryDate returns RangedMarketRangedMarketLeftMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetExpiryDate() string { return v.ExpiryDate }

// GetIsOpen returns RangedMarketRangedMarketLeftMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns RangedMarketRangedMarketLeftMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns RangedMarketRangedMarketLeftMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetLongAddress() string { return v.LongAddress }

// GetShortAddress returns RangedMarketRangedMarketLeftMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetShortAddress() string { return v.ShortAddress }

// GetResult returns RangedMarketRangedMarketLeftMarket.Result, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetResult() int { return v.Result }

// GetCustomMarket returns RangedMarketRangedMarketLeftMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetCustomMarket() bool { return v.CustomMarket }

// GetCustomOracle returns RangedMarketRangedMarketLeftMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetCustomOracle() string { return v.CustomOracle }

// GetFinalPrice returns RangedMarketRangedMarketLeftMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketLeftMarket) GetFinalPrice() string { return v.FinalPrice }

// RangedMarketRangedMarketRightMarket includes the requested fields of the GraphQL type Market.
type RangedMarketRangedMarketRightMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns RangedMarketRangedMarketRightMarket.Id, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetId() string { return v.Id }

// GetTimestamp returns RangedMarketRangedMarketRightMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns RangedMarketRangedMarketRightMarket.Creator, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns RangedMarketRangedMarketRightMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetStrikePrice returns RangedMarketRangedMarketRightMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetStrikePrice() string { return v.StrikePrice }

// GetMaturityDate returns RangedMarketRangedMarketRightMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetMaturityDate() string { return v.MaturityDate }

// GetExpiryDate returns RangedMarketRangedMarketRightMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetExpiryDate() string { return v.ExpiryDate }

// GetIsOpen returns RangedMarketRangedMarketRightMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns RangedMarketRangedMarketRightMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns RangedMarketRangedMarketRightMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetLongAddress() string { return v.LongAddress }

// GetShortAddress returns RangedMarketRangedMarketRightMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetShortAddress() string { return v.ShortAddress }

// GetResult returns RangedMarketRangedMarketRightMarket.Result, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetResult() int { return v.Result }

// GetCustomMarket returns RangedMarketRangedMarketRightMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetCustomMarket() bool { return v.CustomMarket }

// GetCustomOracle returns RangedMarketRangedMarketRightMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetCustomOracle() string { return v.CustomOracle }

// GetFinalPrice returns RangedMarketRangedMarketRightMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketRangedMarketRightMarket) GetFinalPrice() string { return v.FinalPrice }

// RangedMarketResponse is returned by RangedMarket on success.
type RangedMarketResponse struct {
	RangedMarket RangedMarketRangedMarket `json:"rangedMarket"`
}

// GetRangedMarket returns RangedMarketResponse.RangedMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketResponse) GetRangedMarket() RangedMarketRangedMarket { return v.RangedMarket }

// RangedMarketsRangedMarketsRangedMarket includes the requested fields of the GraphQL type RangedMarket.
type RangedMarketsRangedMarketsRangedMarket struct {
	Id           string                                            `json:"id"`
	Timestamp    string                                            `json:"timestamp"`
	CurrencyKey  string                                            `json:"currencyKey"`
	MaturityDate string                                            `json:"maturityDate"`
	LeftPrice    string                                            `json:"leftPrice"`
	RightPrice   string                                            `json:"rightPrice"`
	InAddress    string                                            `json:"inAddress"`
	OutAddress   string                                            `json:"outAddress"`
	RightMarket  RangedMarketsRangedMarketsRangedMarketRightMarket `json:"rightMarket"`
	LeftMarket   RangedMarketsRangedMarketsRangedMarketLeftMarket  `json:"leftMarket"`
	IsOpen       bool                                              `json:"isOpen"`
	Result       int                                               `json:"result"`
	FinalPrice   string                                            `json:"finalPrice"`
}

// GetId returns RangedMarketsRangedMarketsRangedMarket.Id, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetId() string { return v.Id }

// GetTimestamp returns RangedMarketsRangedMarketsRangedMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetTimestamp() string { return v.Timestamp }

// GetCurrencyKey returns RangedMarketsRangedMarketsRangedMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetCurrencyKey() string { return v.CurrencyKey }

// GetMaturityDate returns RangedMarketsRangedMarketsRangedMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetMaturityDate() string { return v.MaturityDate }

// GetLeftPrice returns RangedMarketsRangedMarketsRangedMarket.LeftPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetLeftPrice() string { return v.LeftPrice }

// GetRightPrice returns RangedMarketsRangedMarketsRangedMarket.RightPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetRightPrice() string { return v.RightPrice }

// GetInAddress returns RangedMarketsRangedMarketsRangedMarket.InAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetInAddress() string { return v.InAddress }

// GetOutAddress returns RangedMarketsRangedMarketsRangedMarket.OutAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetOutAddress() string { return v.OutAddress }

// GetRightMarket returns RangedMarketsRangedMarketsRangedMarket.RightMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetRightMarket() RangedMarketsRangedMarketsRangedMarketRightMarket {
	return v.RightMarket
}

// GetLeftMarket returns RangedMarketsRangedMarketsRangedMarket.LeftMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetLeftMarket() RangedMarketsRangedMarketsRangedMarketLeftMarket {
	return v.LeftMarket
}

// GetIsOpen returns RangedMarketsRangedMarketsRangedMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetIsOpen() bool { return v.IsOpen }

// GetResult returns RangedMarketsRangedMarketsRangedMarket.Result, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetResult() int { return v.Result }

// GetFinalPrice returns RangedMarketsRangedMarketsRangedMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarket) GetFinalPrice() string { return v.FinalPrice }

// RangedMarketsRangedMarketsRangedMarketLeftMarket includes the requested fields of the GraphQL type Market.
type RangedMarketsRangedMarketsRangedMarketLeftMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns RangedMarketsRangedMarketsRangedMarketLeftMarket.Id, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetId() string { return v.Id }

// GetTimestamp returns RangedMarketsRangedMarketsRangedMarketLeftMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns RangedMarketsRangedMarketsRangedMarketLeftMarket.Creator, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns RangedMarketsRangedMarketsRangedMarketLeftMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetCurrencyKey() string {
	return v.CurrencyKey
}

// GetStrikePrice returns RangedMarketsRangedMarketsRangedMarketLeftMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetStrikePrice() string {
	return v.StrikePrice
}

// GetMaturityDate returns RangedMarketsRangedMarketsRangedMarketLeftMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetMaturityDate() string {
	return v.MaturityDate
}

// GetExpiryDate returns RangedMarketsRangedMarketsRangedMarketLeftMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetExpiryDate() string {
	return v.ExpiryDate
}

// GetIsOpen returns RangedMarketsRangedMarketsRangedMarketLeftMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns RangedMarketsRangedMarketsRangedMarketLeftMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns RangedMarketsRangedMarketsRangedMarketLeftMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetLongAddress() string {
	return v.LongAddress
}

// GetShortAddress returns RangedMarketsRangedMarketsRangedMarketLeftMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetShortAddress() string {
	return v.ShortAddress
}

// GetResult returns RangedMarketsRangedMarketsRangedMarketLeftMarket.Result, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetResult() int { return v.Result }

// GetCustomMarket returns RangedMarketsRangedMarketsRangedMarketLeftMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetCustomMarket() bool {
	return v.CustomMarket
}

// GetCustomOracle returns RangedMarketsRangedMarketsRangedMarketLeftMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetCustomOracle() string {
	return v.CustomOracle
}

// GetFinalPrice returns RangedMarketsRangedMarketsRangedMarketLeftMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketLeftMarket) GetFinalPrice() string {
	return v.FinalPrice
}

// RangedMarketsRangedMarketsRangedMarketRightMarket includes the requested fields of the GraphQL type Market.
type RangedMarketsRangedMarketsRangedMarketRightMarket struct {
	Id           string `json:"id"`
	Timestamp    string `json:"timestamp"`
	Creator      string `json:"creator"`
	CurrencyKey  string `json:"currencyKey"`
	StrikePrice  string `json:"strikePrice"`
	MaturityDate string `json:"maturityDate"`
	ExpiryDate   string `json:"expiryDate"`
	IsOpen       bool   `json:"isOpen"`
	PoolSize     string `json:"poolSize"`
	LongAddress  string `json:"longAddress"`
	ShortAddress string `json:"shortAddress"`
	Result       int    `json:"result"`
	CustomMarket bool   `json:"customMarket"`
	CustomOracle string `json:"customOracle"`
	FinalPrice   string `json:"finalPrice"`
}

// GetId returns RangedMarketsRangedMarketsRangedMarketRightMarket.Id, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetId() string { return v.Id }

// GetTimestamp returns RangedMarketsRangedMarketsRangedMarketRightMarket.Timestamp, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetTimestamp() string { return v.Timestamp }

// GetCreator returns RangedMarketsRangedMarketsRangedMarketRightMarket.Creator, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetCreator() string { return v.Creator }

// GetCurrencyKey returns RangedMarketsRangedMarketsRangedMarketRightMarket.CurrencyKey, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetCurrencyKey() string {
	return v.CurrencyKey
}

// GetStrikePrice returns RangedMarketsRangedMarketsRangedMarketRightMarket.StrikePrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetStrikePrice() string {
	return v.StrikePrice
}

// GetMaturityDate returns RangedMarketsRangedMarketsRangedMarketRightMarket.MaturityDate, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetMaturityDate() string {
	return v.MaturityDate
}

// GetExpiryDate returns RangedMarketsRangedMarketsRangedMarketRightMarket.ExpiryDate, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetExpiryDate() string {
	return v.ExpiryDate
}

// GetIsOpen returns RangedMarketsRangedMarketsRangedMarketRightMarket.IsOpen, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetIsOpen() bool { return v.IsOpen }

// GetPoolSize returns RangedMarketsRangedMarketsRangedMarketRightMarket.PoolSize, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetPoolSize() string { return v.PoolSize }

// GetLongAddress returns RangedMarketsRangedMarketsRangedMarketRightMarket.LongAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetLongAddress() string {
	return v.LongAddress
}

// GetShortAddress returns RangedMarketsRangedMarketsRangedMarketRightMarket.ShortAddress, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetShortAddress() string {
	return v.ShortAddress
}

// GetResult returns RangedMarketsRangedMarketsRangedMarketRightMarket.Result, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetResult() int { return v.Result }

// GetCustomMarket returns RangedMarketsRangedMarketsRangedMarketRightMarket.CustomMarket, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetCustomMarket() bool {
	return v.CustomMarket
}

// GetCustomOracle returns RangedMarketsRangedMarketsRangedMarketRightMarket.CustomOracle, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetCustomOracle() string {
	return v.CustomOracle
}

// GetFinalPrice returns RangedMarketsRangedMarketsRangedMarketRightMarket.FinalPrice, and is useful for accessing the field via an interface.
func (v *RangedMarketsRangedMarketsRangedMarketRightMarket) GetFinalPrice() string {
	return v.FinalPrice
}

// RangedMarketsResponse is returned by RangedMarkets on success.
type RangedMarketsResponse struct {
	RangedMarkets []RangedMarketsRangedMarketsRangedMarket `json:"rangedMarkets"`
}

// GetRangedMarkets returns RangedMarketsResponse.RangedMarkets, and is useful for accessing the field via an interface.
func (v *RangedMarketsResponse) GetRangedMarkets() []RangedMarketsRangedMarketsRangedMarket {
	return v.RangedMarkets
}

// __AllMarketsInput is used internally by genqlient
type __AllMarketsInput struct {
	Skip  int `json:"skip"`
	First int `json:"first"`
}

// GetSkip returns __AllMarketsInput.Skip, and is useful for accessing the field via an interface.
func (v *__AllMarketsInput) GetSkip() int { return v.Skip }

// GetFirst returns __AllMarketsInput.First, and is useful for accessing the field via an interface.
func (v *__AllMarketsInput) GetFirst() int { return v.First }

// __AllRangedMarketsInput is used internally by genqlient
type __AllRangedMarketsInput struct {
	Skip  int `json:"skip"`
	First int `json:"first"`
}

// GetSkip returns __AllRangedMarketsInput.Skip, and is useful for accessing the field via an interface.
func (v *__AllRangedMarketsInput) GetSkip() int { return v.Skip }

// GetFirst returns __AllRangedMarketsInput.First, and is useful for accessing the field via an interface.
func (v *__AllRangedMarketsInput) GetFirst() int { return v.First }

// __MarketInput is used internally by genqlient
type __MarketInput struct {
	Id string `json:"id"`
}

// GetId returns __MarketInput.Id, and is useful for accessing the field via an interface.
func (v *__MarketInput) GetId() string { return v.Id }

// __MarketsInput is used internally by genqlient
type __MarketsInput struct {
	Skip  int    `json:"skip"`
	First int    `json:"first"`
	T     string `json:"t"`
}

// GetSkip returns __MarketsInput.Skip, and is useful for accessing the field via an interface.
func (v *__MarketsInput) GetSkip() int { return v.Skip }

// GetFirst returns __MarketsInput.First, and is useful for accessing the field via an interface.
func (v *__MarketsInput) GetFirst() int { return v.First }

// GetT returns __MarketsInput.T, and is useful for accessing the field via an interface.
func (v *__MarketsInput) GetT() string { return v.T }

// __RangedMarketInput is used internally by genqlient
type __RangedMarketInput struct {
	Id string `json:"id"`
}

// GetId returns __RangedMarketInput.Id, and is useful for accessing the field via an interface.
func (v *__RangedMarketInput) GetId() string { return v.Id }

// __RangedMarketsInput is used internally by genqlient
type __RangedMarketsInput struct {
	Skip  int    `json:"skip"`
	First int    `json:"first"`
	T     string `json:"t"`
}

// GetSkip returns __RangedMarketsInput.Skip, and is useful for accessing the field via an interface.
func (v *__RangedMarketsInput) GetSkip() int { return v.Skip }

// GetFirst returns __RangedMarketsInput.First, and is useful for accessing the field via an interface.
func (v *__RangedMarketsInput) GetFirst() int { return v.First }

// GetT returns __RangedMarketsInput.T, and is useful for accessing the field via an interface.
func (v *__RangedMarketsInput) GetT() string { return v.T }

func AllLive(
	ctx context.Context,
	client graphql.Client,
) (*AllLiveResponse, error) {
	req := &graphql.Request{
		OpName: "AllLive",
		Query: `
query AllLive {
	markets(where: {result:null}) {
		id
		timestamp
		creator
		currencyKey
		strikePrice
		maturityDate
		expiryDate
		isOpen
		result
		longAddress
		shortAddress
		finalPrice
	}
}
`,
	}
	var err error

	var data AllLiveResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func AllMarkets(
	ctx context.Context,
	client graphql.Client,
	skip int,
	first int,
) (*AllMarketsResponse, error) {
	req := &graphql.Request{
		OpName: "AllMarkets",
		Query: `
query AllMarkets ($skip: Int, $first: Int) {
	markets(skip: $skip, first: $first, orderBy: timestamp, orderDirection: desc) {
		id
		timestamp
		creator
		currencyKey
		strikePrice
		maturityDate
		expiryDate
		isOpen
		poolSize
		longAddress
		shortAddress
		result
		customMarket
		customOracle
		finalPrice
	}
}
`,
		Variables: &__AllMarketsInput{
			Skip:  skip,
			First: first,
		},
	}
	var err error

	var data AllMarketsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func AllRangedMarkets(
	ctx context.Context,
	client graphql.Client,
	skip int,
	first int,
) (*AllRangedMarketsResponse, error) {
	req := &graphql.Request{
		OpName: "AllRangedMarkets",
		Query: `
query AllRangedMarkets ($skip: Int, $first: Int) {
	rangedMarkets(skip: $skip, first: $first, orderBy: timestamp, orderDirection: desc) {
		id
		timestamp
		currencyKey
		maturityDate
		leftPrice
		rightPrice
		inAddress
		outAddress
		rightMarket {
			id
			timestamp
			creator
			currencyKey
			strikePrice
			maturityDate
			expiryDate
			isOpen
			poolSize
			longAddress
			shortAddress
			result
			customMarket
			customOracle
			finalPrice
		}
		leftMarket {
			id
			timestamp
			creator
			currencyKey
			strikePrice
			maturityDate
			expiryDate
			isOpen
			poolSize
			longAddress
			shortAddress
			result
			customMarket
			customOracle
			finalPrice
		}
		isOpen
		result
		finalPrice
	}
}
`,
		Variables: &__AllRangedMarketsInput{
			Skip:  skip,
			First: first,
		},
	}
	var err error

	var data AllRangedMarketsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func Market(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*MarketResponse, error) {
	req := &graphql.Request{
		OpName: "Market",
		Query: `
query Market ($id: ID!) {
	market(id: $id) {
		timestamp
		creator
		currencyKey
		strikePrice
		maturityDate
		expiryDate
		isOpen
		poolSize
		longAddress
		shortAddress
		result
		customMarket
		customOracle
		finalPrice
	}
}
`,
		Variables: &__MarketInput{
			Id: id,
		},
	}
	var err error

	var data MarketResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func Markets(
	ctx context.Context,
	client graphql.Client,
	skip int,
	first int,
	t string,
) (*MarketsResponse, error) {
	req := &graphql.Request{
		OpName: "Markets",
		Query: `
query Markets ($skip: Int, $first: Int, $t: BigInt) {
	markets(skip: $skip, first: $first, orderBy: timestamp, orderDirection: desc, where: {timestamp_gt:$t}) {
		id
		timestamp
		creator
		currencyKey
		strikePrice
		maturityDate
		expiryDate
		isOpen
		poolSize
		longAddress
		shortAddress
		result
		customMarket
		customOracle
		finalPrice
	}
}
`,
		Variables: &__MarketsInput{
			Skip:  skip,
			First: first,
			T:     t,
		},
	}
	var err error

	var data MarketsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func RangedMarket(
	ctx context.Context,
	client graphql.Client,
	id string,
) (*RangedMarketResponse, error) {
	req := &graphql.Request{
		OpName: "RangedMarket",
		Query: `
query RangedMarket ($id: ID!) {
	rangedMarket(id: $id) {
		timestamp
		currencyKey
		maturityDate
		leftPrice
		rightPrice
		inAddress
		outAddress
		rightMarket {
			id
			timestamp
			creator
			currencyKey
			strikePrice
			maturityDate
			expiryDate
			isOpen
			poolSize
			longAddress
			shortAddress
			result
			customMarket
			customOracle
			finalPrice
		}
		leftMarket {
			id
			timestamp
			creator
			currencyKey
			strikePrice
			maturityDate
			expiryDate
			isOpen
			poolSize
			longAddress
			shortAddress
			result
			customMarket
			customOracle
			finalPrice
		}
		isOpen
		result
		finalPrice
	}
}
`,
		Variables: &__RangedMarketInput{
			Id: id,
		},
	}
	var err error

	var data RangedMarketResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func RangedMarkets(
	ctx context.Context,
	client graphql.Client,
	skip int,
	first int,
	t string,
) (*RangedMarketsResponse, error) {
	req := &graphql.Request{
		OpName: "RangedMarkets",
		Query: `
query RangedMarkets ($skip: Int, $first: Int, $t: BigInt) {
	rangedMarkets(skip: $skip, first: $first, orderBy: timestamp, orderDirection: desc, where: {timestamp_gt:$t}) {
		id
		timestamp
		currencyKey
		maturityDate
		leftPrice
		rightPrice
		inAddress
		outAddress
		rightMarket {
			id
			timestamp
			creator
			currencyKey
			strikePrice
			maturityDate
			expiryDate
			isOpen
			poolSize
			longAddress
			shortAddress
			result
			customMarket
			customOracle
			finalPrice
		}
		leftMarket {
			id
			timestamp
			creator
			currencyKey
			strikePrice
			maturityDate
			expiryDate
			isOpen
			poolSize
			longAddress
			shortAddress
			result
			customMarket
			customOracle
			finalPrice
		}
		isOpen
		result
		finalPrice
	}
}
`,
		Variables: &__RangedMarketsInput{
			Skip:  skip,
			First: first,
			T:     t,
		},
	}
	var err error

	var data RangedMarketsResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
